### ISSUE TITLE
Juno can't find nw.gui

### ISSUE THREAD

**Issue by guidocalvano** [one-more-minute/Julia-LT#217]
Error loading JS file: /Users/guidocalvano/Library/Application Support/LightTable/plugins/Juno/juno_compiled.js : Error: Cannot find module 'nw.gui'
bootstrap.js [30084]    lt.objs.plugins.__BEH__load_js

My OS is Mac OSX 10.9.4

The julia I use:
[:app :lt.objs.langs.julia/julia-path "/Applications/Julia-0.4.2.app/Contents/Resources/julia/bin/julia"]

**Comment by atayuksel** [comment]
I have the same issue. Should I install nw.gui manually or there is a problem with the path.

**Comment by MikeInnes** [comment]
Could you try re-downloading the latest Juno from the julialang.org website?

**Comment by leowmjw** [comment]
Facing same problem; also OSX Mavericks.  Installed onto latest LightTable via Juno plugin:

```
Error loading JS file: /Users/leow/Library/Application Support/LightTable/plugins/Juno/juno_compiled.js : Error: Cannot find module 'nw.gui'
Error: Cannot find module 'nw.gui'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at eval (/Users/leow/Library/Application%20Support/LightTable/plugins/Juno/juno_compiled.js:33:30)
    at eval (native)
    at c (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21436:41)
    at a (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21444:18)
    at Function.lt.objs.plugins.__BEH__load_js (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:29874:33)
    at c (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
[:app :lt.objs.settings/pair-keymap-diffs] is deprecated and will be removed in 0.9.0. Use [:editor :lt.objs.editor/autoclose-brackets] instead
```

**Comment by effranco** [comment]
The problem is with the "if" statements at lines "26" and "30" of the file "juno_compiled.js".

I think that the "lt.objs.platform.atom_shell" is not defined anymore in LT.

I forced this two "ifs" to be true (I'm only using Juno as a LT plugin) and the errors messages disappeared.

**Comment by MikeInnes** [comment]
I encourage everyone to try out the new atom work at http://junolab.org. These issues are unlikely to get fixed.
