### ISSUE TITLE
invalid behaviour of unregister-result

### ISSUE THREAD

**Issue by palango** [one-more-minute/Julia-LT#95]
When running a julia file I get the following backtrace in the console.

```
"Invalid behavior: :lt.objs.langs.julia.results/unregister-result"
Error: No protocol method IDeref.-deref defined for type null: 
    at Error (<anonymous>)
    at cljs.core.missing_protocol (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:1460:10)
    at cljs.core._deref (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2181:38)
    at cljs.core.deref (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:12879:27)
    at Function.__BEH__unregister_result (/Users/paul/Library/Application%20Support/LightTable/plugins/Julia/julia_compiled.js:2205:315)
    at c (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6236:18)
    at lt.object.raise_STAR_ (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20559:74)
    at a (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20592:34)
    at b (file:///Users/paul/Downloads/LightTable%202/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20596:14)
```

**Comment by ghost** [comment]
Just noticed, this thread is dated almost a year and a half.
Is there a solution to this issue? I am getting the same error today.
Although the program works, the output appears along with this error.

**Comment by pfitzseb** [comment]
I'm pretty sure there's not going to be any more work put into Juno/LT. Instead, use [Juno/Atom](http://junolab.org/), which is under active development and should be almost at feature parity with Juno/LT.
